#ifndef NEDRYSOFT_COUNTER_COUNTERSPEC_H
#define NEDRYSOFT_COUNTER_COUNTERSPEC_H

#if defined(NEDRYSOFT_COMPONENT_COUNTER_EXPORT)
#define NEDRYSOFT_COUNTER_DLLSPEC Q_DECL_EXPORT
#else
#define NEDRYSOFT_COUNTER_DLLSPEC Q_DECL_IMPORT
#endif

#endif // NEDRYSOFT_COUNTER_COUNTERSPEC_H 